README.md
- Added table of contents
- Added install instructions (these may be somewhat incorrect until other PRs are merged in)
- Added basic usage (documented some features that haven't been implemented yet but should be before open sourcing)
=> Update Readme with install and usage instructions

package-lock.json, package.json, src/commands/install.js, src/commands/remove.js, src/common/utils.js, src/index.js
- npm install
- make install
- install a version of yarn using `yvm install <version>`
- remove the version using `yvm remove <version>` and ensure that `~/.yvm/versions/v<version>` does not exist anymore
=> Yvm remove

.eslintrc.json, src/index.js, src/util/version.js, yvm.sh
- `make install && source /usr/local/bin/yvm`
- `echo 1.6.0 > .yvmrc`
- `yvm install 1.7.0` should install 1.7.0
- `yvm install` should install 1.6.0
- `yvm exec 1.7.0 versions` should use 1.7.0
- `yvm exec versions` should use 1.6.0
- `yvm use 1.7.0` should install 1.7.0
- `yvm use` should install 1.6.0
=> yvmrc support

src/commands/listRemote.js, src/common/utils.js, src/index.js
- Add command to list installable versions
- Add helper to strip version prefix
- Run `yvm ls-remote` or `yvm list-remote`
- Verify that the listed versions match those listed here: https://github.com/yarnpkg/yarn/tags
- Some versions listed don't seem to be downloadable.
- This doesn't list nightly builds
- This doesn't indicate which versions are LTS, Stable, or pre-release
=> List versions available for install

docs/API.md, src/index.js
Addresses #49, #51, and #50 
- Add aliases for install, remove, and list
- Add descriptions for commands
- Show help when no params provided
- Update API docs
- Run `yvm`
- Verify help is shown, and that aliases and descriptions added
- Run `yvm i` and ensure it calls install
- Run `yvm rm` and ensure it calls remove
- Run `yvm ls` and ensure it calls list
=> Improve command line UX

Makefile
=> easier development, make development better

docs/API.md, src/index.js
Addresses #53 
- Add help command (which does the same thing as `yvm`, `yvm -h`, and `yvm --help`)
- Update API docs
1. Run `yvm help`
- Verify that help text is outputted
=> Add help command

Makefile, webpack/webpack.config.dev.js
- Makes re-compiling faster
- `make install-watch`
- Edit a file and save, webpack should compile the new code nearly instantly
=> Use dev mode when watching

src/common/utils.js
half 🚨 : This is blocking the dogfooding release
=> Use YVM_DIR

src/commands/remove.js, src/index.js
- Install and use one version of yarn
- Try running `yvm remove <version>`, it should fail
- Install and use a different version
- Try deleting previous yarn version, it should succeed
=> prevent removing currently active version

src/yvm.js
- Remove `.yvmrc` file
- Run `yvm exec list`
=> better error handling

.circleci/config.yml, src/yvm.sh
- Delete all your yarn versions
- `unset -f yvm`
- `yvm use` should fail
- `source /usr/local/bin/yvm`
- `yvm use` should auto-install 1.7.0
=> Prevent yvm use when not a shell script; add auto-install to yvm use

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Basic bug and feature issue templates
=> Add bug and feature templates

README.md, webpack/webpack.config.base.js
Add node 4.8 target to babel, updated readme
=> target node 4.8

Makefile, scripts/install.sh
- Removes eager use if yvm in makefile
- Auto-install release version of yvm if not already installed globally
- `rm -r $YVM_DIR`
- `rm /usr/local/bin/yvm`
- `make clean`
- `make node_modules` the first time should install yvm
- There should not be an error like `/usr/local/bin/yvm: line 3: $1: unbound variable`
- `make node_modules` the second time should just run
=> improve makefile, fix install script

src/yvm.sh
- Prints the new version of yarn on `yvm use`
- `yvm use 1.7.0` should print `Now using yarn version 1.7.0`
=> Print new version on `yvm use`

.circleci/config.yml, .github/ISSUE_TEMPLATE/bug_report.md, AUTHORS, CONTRIBUTING.md, README.md, package.json, scripts/install.sh, src/yvm.sh
Switching from github.com/tophatmonocle to github.com/tophat
=> chore: org transfer

README.md
Giving credit, dropping copyright from README (this is covered under our LICENCE file)
=> docs: give credit + drop copyright from README

README.md
=> Only report build status from master

.all-contributorsrc, .github/README.md, package-lock.json, package.json
=> Readme update

.github/README.md
=> Move Badges

.github/README.md
Updated Maturity level and Slack badges
=> Updated Maturity level and Slack badges

.github/README.md, docs/faq.md
=> Link to code of conduct

src/commands/list.js, src/util/utils.js, test/commands/list.test.js
Yvm List would just show all the installed versions of yarn. It will now also show the currently active version of yarn.
- Run yvm list and make sure the currently active version of yarn is shown.
=> Yvm list show active yarn

.github/ISSUE_TEMPLATE/bug_report.md
Adding additional fields on bug reports
=> pr: additional information on bug reports

package.json, scripts/install.sh, src/commands/yvmVersion.js, src/util/yvmInstalledVersion.js, src/yvm.js, test/util/yvmInstalledVersion.test.js, yarn.lock
Fixes #182.
Need to run the new install `./script/install.sh`
`yvm version`
Should output latest installed version.
=> `yvm version` outputs yvm version

docs/faq.md
It was not clear whether you needed both a package.json and a config file or just one of them.
=> Clearifying the docs on using package.json or config file

Makefile, package.json, scripts/install-watch.sh, scripts/install.sh, webpack/webpack.config.base.js, webpack/webpack.config.production.js, yarn.lock
Currently bundled together for dist, removing this behaviour. 
This completely breaks `yvm exec` but will fix that in a follow up PR (just don't want such a massive PR): (See fix in #213)
=> Split app from node_modules

website/package.json, website/yarn.lock
=> Update docusaurus to 1.6.2

.circleci/config.yml, Makefile, package.json, src/util/utils.js, yarn.lock
Have a circular dep regression #229. Add CI checks to prevent this
=> fix: defend against circular dep

README.md
=> Link to FAQ from readme

README.md, docs/contribute.md
- Update documentation about sourcing yvm.sh in dev mode. Related to #140
=> Update documentation about sourcing yvm

README.md, docs/overview.md, scripts/install.sh
=> feat: support install without GitHub api

scripts/get-version.sh, scripts/install.sh, src/util/utils.js
Use yvm-github-gateway instead of api.github.com.
yvm-github-gateway code is at: https://github.com/tophat/yvm-github-gateway
Fixes #267 and #255
=> feat: use yvm-github-gateway proxy

package.json, yarn.lock
=> infra: greenkeeper/eslint config prettier 3.5.0

README.md, docs/overview.md, src/yvm-exec.js, webpack/webpack.config.base.js
=> BREAKING_CHANGE: lowest support node version is 8.0

src/util/log.js, test/util/__snapshots__/utils.test.js.snap, test/util/utils.test.js
- Allows spying on default log function
- Include console colors in log snapshots
- Verify happy path
- Only test changes
=> test: util log default

package.json, test/commands/install.test.js, yarn.lock
=> Update eslint-plugin-jest to the latest version

package.json
Closes #319 
N/A
- Gets rid of deprecation warning
=> chore: update jest config

.circleci/config.yml, website/package.json
=> chore: deploy website

src/yvm.js
- Changes the order of the commands putting the deprecated at the bottom
=> refactor: move deprecated commands to the bottom

package.json, yarn.lock
Going straight for the newer release.
=> Greenkeeper/semver 6.0.0

package.json, yarn.lock
=> chore(package): update eslint to version 5.16.0

website/package.json, website/yarn.lock
=>  chore(package): update docusaurus to version 1.8.0

README.md
- Add homebrew installation step
=> docs: homebrew installation

.circleci/config.yml, Makefile
- Uses make command in sanity check to ensure `make install` is correctly configured.
=> chore: use make in sanity check

scripts/install.js, scripts/tests/install.test.js
- Removes dependency on curl & mkdir in node installer, for #348.
=> chore: remove curl, mkdir dependency

.github/tap-release.yml
- Adds [tap release app config](https://probot.github.io/apps/tap-release/)
=> chore: auto update yvm tap

package.json, yarn.lock
=> chore: update eslint plugin import 2.17.1

test/sanity-test.sh
- Add simple sanity for shimmed yarn
=> test: shim sanity

.circleci/config.yml
- env cache key added to control reinstalling of node modules
N/A
=> ci: unflake build

package.json, test/commands/alias.test.js, test/commands/configureShell.test.js, test/commands/current.test.js, test/commands/exec.test.js, test/commands/getDefaultVersion.test.js, test/commands/getNewPath.test.js, test/commands/install.test.js, test/commands/list.test.js, test/commands/listRemote.test.js, test/commands/remove.test.js, test/commands/setDefault.test.js, test/commands/unalias.test.js, test/util/alias.test.js, test/util/utils.test.js, test/util/version.test.js, test/util/yvmInstalledVersion.test.js
=> test: absolute imports

src/commands/alias.js, src/commands/configureShell.js, src/commands/current.js, src/commands/exec.js, src/commands/getDefaultVersion.js, src/commands/getNewPath.js, src/commands/install.js, src/commands/list.js, src/commands/listRemote.js, src/commands/remove.js, src/commands/setDefault.js, src/commands/unalias.js, src/commands/which.js, src/util/alias.js, src/util/download.js, src/util/utils.js, src/util/version.js, src/util/yvmInstalledVersion.js, src/yvm.js, webpack/webpack.config.base.js
=> refactor: absolute imports

package.json, src/yvm.js, yarn.lock
=> chore: update prettier to version 1.17.0

docs/api.md
=> docs: update api

package.json, src/commands/exec.js, test/commands/exec.test.js, yarn.lock
=>  chore(package): update all-contributors-cli to version 6.3.1

.bundlewatch.config.js, .github/tap-release.yml, package.json, scripts/install-watch.sh, webpack/webpack.config.base.js, webpack/webpack.config.dev.js, webpack/webpack.config.prod.js, yarn.lock
Closes #233 
- `yvm --help` then test each command
- `make build-production`
- `make bundlewatch`
=> chore: decrease release size

package.json, scripts/tests/install.test.js, src/commands/configureShell.js, test/commands/configureShell.test.js, yarn.lock
Use mock props package in tests
=> chore: use mock props in tests

package.json, yarn.lock
=> chore: update husky to the latest version 🚀 #380

scripts/install.js, scripts/tests/install.test.js
Remove some more system bin dependencies
- One step closer to a pure node install
=> chore: remove dependency on rm and chmod

test/commands/alias.test.js
Fix stable version in alias test
=> test: alias pin stable version

package.json, yarn.lock
=>  chore(package): update eslint-plugin-prettier to version 3.1.0

package.json, yarn.lock
=> chore(package): update codecov to version 3.5.0

package.json, yarn.lock
=> Greenkeeper/eslint plugin jest 22.6.3

yarn.lock
Refresh yarn lock file to eliminate reported `yarn audit` vulnerabilities from outdated branch dependencies
- `yarn audit` see reported issues
- `git checkout <this-branch>`
- `yarn audit` no reported issues 🎉 
- 🆕
=> chore: refresh yarn lock

package.json, scripts/install.js, yarn.lock
=>  chore(package): update prettier to version 1.18.0

Makefile, package.json, yarn.lock
=>  chore(package): update bundlewatch to version 0.2.2

package.json, yarn.lock
Closes #396. Update semantic release github plugin to get fix.
- How to test... 🤔
=> chore: fix tap release

package.json, src/yvm.js, webpack/webpack.config.base.js, yarn.lock
Closes #419 
Updates babel package group and replaces babel polyfill as per [instructions](https://babeljs.io/docs/en/babel-polyfill)
- `make install-watch`
- `yvm help`
- Run all commands and confirm no breaking changes
- https://github.com/babel/babel/pull/7646
=> chore(package): update babel7 to latest version 🚀

package.json, yarn.lock
Refresh yarn lock to eliminate reported vulnerabilities
Update husky hooks
N/A
=> chore: refresh yarn lock deps

.releaserc.js, CHANGELOG.md, package.json, yarn.lock
Semantic release build steps and changelog
n/a
=> chore: auto changelog updates

src/commands/configureShell.js, test/commands/__snapshots__/configureShell.test.js.snap, test/commands/configureShell.test.js
=> fix: do not configure the custom profile for multiple shells

package.json
Check yarn lock file in pre-commit stage
=> chore: yarn deduplicate

README.md
- Updated the readme to include a note about `--without-node` mentioned in issue #206
=> docs: include note about --without-node

yarn.lock
=> chore: upgrade all theslint

website/package.json, website/yarn.lock
Fixes https://github.com/tophat/yvm/network/alert/website/yarn.lock/set-value/open
=> chore: update website dependencies

package.json, yarn.lock
=> chore(package): update semantic-release to latest versions

src/commands/current.js, test/commands/current.test.js
Fixes #486 
- install yvm release version
- create package json with `"engines": { "yarn": ">=1.16.0" }`
- `yvm current` should show that it matches
- create package json with `"engines": { "yarn": "<=1.16.0" }`
- `yvm current` should show that it does not match
=> fix: check for semver satisfaction of yvm config

.github/workflows/auto-approve.yml
Adding auto approve action for dependabot spam
=> ci: add auto approve github action

test/scripts/yvm.test.fish, test/scripts/yvm.test.sh
=> test: shim and fish sanities

.github/workflows/ci.yml, README.md, src/commands/exec.js, test/commands/exec.test.js, test/scripts/yvm.test.fish, test/scripts/yvm.test.sh, yarn.lock
Adds ability to customize the yvm exec bootstrap, closes #900.
See the bash sanity.
=> feat: add custom bootstrap script support

.github/workflows/ci.yml
Fixes bad release job by restoring build artifacts so assets can be attached to the release.
=> fix: release yvm with build assets

package.json, webpack/webpack.config.prod.js, yarn.lock
Replaces obsolete webpack zip plugin
- N/A
- https://github.com/lucduong/webpack-zip-files-plugin/issues/6
=> build: replace webpack zip plugin

README.md
Swaps the discontinued Slack for Discord
=> chore: remove slack badge, add discord

.github/workflows/dependabot.yml
Dependabot currently only automerges devdeps. This will help clear up the backlog of PRs here so that the ones that require attention are the only ones left.
=> ci: autoapprove token

README.md
=> chore: deprecate yvm in favour of corepack
