tophat/yvm

package.json

Now that the install script is working and we have a makefile, we don't need these any more

Remove package.json scripts

---

.eslintrc.json
src/commands/exec.js
src/commands/install.js
src/commands/list.js
src/commands/remove.js
src/common/log.js
src/common/utils.js
src/index.js

- Auto install for ease
- Use stderr to avoid polluting `yarn` output
- `yvm exec 1.7.0 versions` should install 1.7.0, then output the result of the command
- Running it again should use the installed version
- `yvm exec bin 2> /dev/null` should not print anything that `yarn` itself doesn't print

Auto-install and use stderr

---

src/index.js

Addresses #54 
- Add wildcard command that gets executed if no other command is matched
- Show warning and output help
- Try running yvm with an invalid command
- Verify that it tells you that the command is invalid
- Verify that it prints out help string

Show help on invalid command

---

src/yvm.sh

According to https://www.gnu.org/software/bash/manual/html_node/Is-this-Shell-Interactive_003f.html, the old and new methods should be equivalent, but on CircleCI, $PS1 is set even in non-interactive shells

Better interactive shell detection

---

src/commands/exec.js

🚨 The `require` call is breaking the built bundle

Fix broken webpack bundle

---

scripts/install.sh

- Add line to source yvm in `.bash_profile
- Open bash
- Start fresh:
- `rm /usr/local/bin/yvm`
- `rm -rf ~/.yvm`
- Remove yvm versions from PATH
- Remove lines that source yvm in `~/.bash_profile` if it exists
- Run `type yvm`
- Verify that it says `yvm is a function`
- Check that yvm is sourced in `~/.bash_profile`
- Check that you can use `yvm use` correctly

Source yvm in .bash_profile during install

---

src/commands/install.js
src/commands/listRemote.js
src/common/utils.js

- Moved request for yarn tags to be a util function
- Updated list-remote to use the util function
- Updated install to use the util function to check if the user's version matches what we support
- support for versions greater than 1.0.0
- `yvm install 1.7.0` should work
- `yvm install 1.9.0` should not work
- `yvm install `0.28.4` should not work
- ensure `yvm list-remote` works as expected (displays all valid versions over 1.0.0)

Validate install version is >= 1.0.0

---

src/index.js

Addresses #60. 
- Run `yvm help`
- Verify that `use` command is listed with message
- Run `node ~/.yvm/yvm.js use`
- Verify that user is warned that they shouldn't call the JS file directly

Add `yvm use` to help and warn if user tries to run directly using Node

---

src/commands/list.js

Addresses #72 
- Run `yvm list` and then `yvm list-remote`
- Verify that version formatting matches

Remove 'v' prefix from versions in `yvm list`

---

src/yvm.js

- Commander ignores unknown args, so grab them straight from process.argv
- Before: `node src/yvm.js exec install --frozen-lockfile` should fail
- After: `node src/yvm.js exec install --frozen-lockfile` should pass

Grab all argv and pass to yarn for exec

---

.circleci/config.yml
Makefile
scripts/install-watch.sh
scripts/install.sh
yarn.lock

- Rather than link the entire `artifacts/webpack_build` folder to `~/.yvm`, I decided to link the files that are actually changing (ie. `yvm.js` and `yvm.sh`). 
- Reasoning behind this that subsequent install commands will install into `artifacts/webpack_build` and removing the link will remove the versions you installed.
- Run `make install-watch`
- Verify that changes to code are updated without having to re-run install
- Stop watcher, run `make install`
- Verify that links are removed, and normal install is completed

Update `make install-watch` and `install.sh` to clean up symlinks

---

scripts/install.sh

- Addresses #44
- Added line in install script to export YVM_DIR in `.bash_profile`
- `rm /usr/local/bin/yvm`
- `rm -rf ~/.yvm`
- Remove yvm from PATH
- Remove yvm from `.bash_profile`
- Start Bash
- Verify that both lines added to `.bash_profile`
```
export YVM_DIR=<yvm path>
source /usr/local/bin/yvm
```
- Run `source ~/.bash_profile
- Run `echo $YVM_DIR`
- Verify that yvm path is outputted

Add YVM_DIR line to .bash_profile

---

CONTRIBUTING.md
README.md
docs/faq.md
package.json
scripts/install-watch.sh
src/util/version.js
yarn.lock

Fixes: Running `yvm exec` in a nested directory, says it can't find the .yvmrc file #108 
Execute `yvm exec --version` in a directory with a `.yvmrc`, in a directory outside, and in a sub directory. Verify behaviour is correct.

Add support for search up directories for .yvmrc (as well as looking in package.json etc)

---

src/commands/install.js
src/commands/listRemote.js
src/commands/which.js
src/common/log.js
src/util/version.js
src/yvm-exec.js
src/yvm.js

- Info logging that's not relevant to the end user is now hidden behind the `YVM_VERBOSE` env var
- `yvm exec 1.7.0 --version` should just print `1.7.0`
- `YVM_VERBOSE=1 yvm exec 1.7.0 --version` should print 
```
Using yarn version: 1.7.0
yarn --version
1.7.0
```

Silence standard log with YVM_VERBOSE

---

src/commands/getNewPath.js
src/commands/getPath.js
src/yvm.js
src/yvm.sh
test/commands/getNewPath.test.js

- Changes `yvm use` to use `yvm get-new-path` under the hood, moving most of the logic into JS for consistency
- Closes #112
- `make install-watch`
- Open a new shell
- `yvm use` should still work
- `yvm get-new-path 1.7.0` should return a PATH string for yarn 1.7.0
- `yvm get-new-path` should use the version in .yvmrc
- `yvm use 1.6.0` then `yvm get-new-path 1.7.0` should edit the existing PATH string, not prepend a new segment to it

Move PATH editing logic to JS

---

src/yvm.sh

- yvm will not automatically use the yarn version specified after installing using `yvm install [version]`
- Run `yvm install [version of your choice]`
- It should set that same version as the current yarn version. 
- Can confirm using `yvm which`

Automatically use the specified version of yarn after installing

---

src/yvm.sh

- Changed `sed` commands to be portable between OS X and Linux
- Run `docker run node:8.11.3-slim`
- Copy the `save_last_used_yarn_version` function into the terminal
- Run `save_last_used_yarn_version`, it should not crash

Make `save_last_used_yarn_version` portable

---

.circleci/config.yml

This small change makes sure Slack notifications are only sent for failure on `master` branch.

Send CircleCI Slack notifications for failures only on master branch

---

src/commands/which.js
test/commands/which.test.js

`yvm which` does not actually show what version of yarn you are currently using. This fixes that.
- Make sure some version of yarn is enabled.
- Run `yvm which`. It should display the version of yarn you are currently using.

Show yarn version number to which command

---

src/yvm.js

Addresses #183. 
`yvm` should output help once
`yvm help` should continue to work

fix: double help/usage output when calling yvm

---

src/util/version.js
src/yvm.js
src/yvm.sh
test/util/version.test.js

Motivation was originally to fix #181 + #180 . Found a better approach which works in a few more cases. 
Removes the need for #134 + #163 
Fixes #181 + #180 
This approach sets a global yvm yarn version. Then any command run will look for the yvm version to use as follows:
- Looks for version in command string
- Looks for rcfile
- Looks for global version
- Install the latest version and .sh commands.
- Open a new shell (Should see the please set default version)
- Follow the instructions and open a new terminal, should load and have a default version of yarn set
- If you have a .yarnrc in the folder your shell opened up in, will set to that yarn version
- All commands such as yvm use, yvm install etc will follow the approach of:
- Looks for version in command string
- Looks for rcfile
- …

feat: add global yarn version, remove concept of last used version

---

.circleci/config.yml
Makefile

Reverts tophat/yvm#199
This is an issue on greenkeepers end:
https://github.com/greenkeeperio/greenkeeper/issues/981

Revert "fix: make sure greenkeeper can generate lockfiles"

---

.circleci/config.yml
.eslintignore
Makefile

- Pulls creation of `node_modules_production` to new make task
- Removes duplication install of `node_modules`
- Removes test information
- Run `make build-production`, it should produce the same artifacts before and after this PR

Clean up creation of prod node_modules

---

scripts/install.sh
scripts/release.js
webpack/webpack.config.production.js

- A bug in https://www.npmjs.com/package/webpack-zip-files-plugin makes it include the output file in itself if the file is created in the directory being zipped up
- This PR changes the output path of `yvm.zip` to be `./artifacts/yvm.zip` instead of `./artifacts/webpack_build/yvm.zip`
- This PR also forces `unzip` to overwrite any files when installing using `make install`. It was already doing that when using the `curl | bash` method
- Running `make install` more than once should not prompt for overwrite, it should just do it.
- The output `yvm.zip` should be located in the `artiacts` directory
- Extracting or listing the contents of `yvm.zip` should not show another `yvm.zip` within

Prevent yvm.zip from including itself; force overwrite in dev install

---

src/yvm.sh

When opening a new shell in bash, yvm gives the following error:
```
-bash: local: can only be used in a function
```
I believe this fixes it. Still untested.
UPDATE: modified files locally and this does indeed fix the error.

Fix bash error: "local can only be used in a function"

---

src/commands/getNewPath.js
src/commands/install.js
src/commands/list.js
src/commands/listRemote.js
src/commands/remove.js
src/commands/which.js
src/util/install.js
src/util/path.js
src/util/utils.js
src/util/version.js
src/util/yvmInstalledVersion.js
src/yvm-exec.js
test/commands/list.test.js
test/util/utils.test.js

Fix #193 
When printing the version of the yvm installed/available, it should show the default global version
It also moves the path logic out of utils.js to another helper file path.js so that no cyclic dependency is introduced.
- `make Install`
- `yvm list`

Add Global default while printing versions

---

Makefile

Makefile changed to remove node_modules added by production  build
1. Run `make build-production`
2. Check that directory 'node_modules_production` has been created
3. Run `make clean`
2. Check that the directory was removed
Fixes #237

Have 'make clean' remover production-mode node_modules as well (#237)

---

scripts/install.sh
src/yvm.sh

Change the installation script so that it setups bash in .bashrc and not
in .bash_profile. Note that this leaves users that have previously
installed with sourcing in two places - this is acceptable as it does
not bring harm, except wasting CPU on parsing the script twice.
Also change the way files are include (both in bash and in zsh), adding
guards if the file exists. This avoids error messages if user at some
point deletes $YVM_DIR.
Installation script:
- install (for bash) in `~/.bashrc`
- add guards (for bash/zsh) against missing file
- check that `~/.bash_profile` is not modified
- check that `~/.bashrc` is modified
- check that `yvm` works by default when launching new shell
- check that `~/.bashrc` and `~/.zshrc` are untouched by second installation
- check that neither bash nor …

Change installation script (#225, #227)

---

package.json

Moved `gh-release` in `package.json` from `dependencies` to `devDependencies`.
1. Check any automated release scripts that they will work after changes. Possibly pruning any caches, as previous version may be left behind after this cleanup.
Fixes #245

Move gh-release to devDependencies

---

.circleci/config.yml
package.json
webpack/webpack.config.development.js
yarn.lock

We should automatically source yvm.sh in dev mode whenever any local changes are made. Addresses #140 
- Run `make install-watch`
- Make a change to one of the commands (like adding a console.log somewhere)
- Wait for webpack to build 
- Run the command
- See that your log shows up without explicitly running `source yvm.sh` 🎉

Automatically source yvm.sh in dev mode 

---

scripts/install.sh

The scripts ~/.zshrc and ~/.bashrc should only be modified if already
existing, otherwise assume user does not need those and do not create
them.
Also fixes a problem when nonexisting file would cause installation
script to display error message during installation.
Changed installation script to check for existence of `~/.zshrc` / `~/.bashrc` before invoking `grep` or modifying them.
Check installation when `~/.zshrc` / `~/.bashrc` are or are not present in user's home directory.
Fixes #228

Don't create shell init scripts if not needed

---

src/yvm.sh

Make initialization (sourcing from bashrc/zshrc) output only error
messages, silence default messages from yvm use.
Changed `yvm.sh` so that the initialization is quiet, displaying only error messages.
Make sure that initialization is quiet (no message about currently used version), however error messages (e.g. about missing node version) are still present. The message should still be displayed if `yvm use` is used directly.
Please test both `bash` and `zsh`, especially as I don't use `zsh` myself.
Fixes #226

Less verbose initialization

---

.all-contributorsrc
README.md
docs/overview.md
src/commands/install.js
src/yvm.js
test/commands/install.test.js

Give users the option to install the latest version of Yarn. Using `yvm install --latest` or `yvm install -l`. 
See #175 
- Run `yvm ls-remote`. Note the latest version of Yarn available 
- Run `yvm install --latest`
- See that the version is installed 
- Run `yvm install --latest` again 
- See that yvm prints a message about version already installed

Create new command to install latest version

---

src/util/install.js

Occasionally seeing the issue in CI:
```
#!/bin/bash -eo pipefail
make node_modules
/home/circleci/.yvm/yvm.sh exec install --frozen-lockfile --ci
/home/circleci/.yvm/yvm-exec.js:1
(function (exports, require, module, __filename, __dirname) { !function(n){var r={};function e(t){if(r[t])return r[t].exports;var o=r[t]={i:t,l:!1,exports:{}};return n[t].call(o.exports,o,o.exports,e),o.l=!0,o.exports}e.m=n,e.c=r,e.d=function(n,r,t){e.o(n,r)||Object.defineProperty(n,r,{enumerable:!0,get:t})},e.r=function(n){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(n,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(n,"__esModule",{value:!0})},e.t=function(n,r){if(1&r&&(n=e(n)),8&r)return n;if(4&r&&"object"==typeof n&&n&&n.__esModule)return n;var …
```

bugfix: fix crash no method s exists

---

src/commands/list.js
src/commands/listRemote.js
src/util/version.js
test/commands/listRemote.test.js
test/util/utils.test.js
test/util/version.test.js

Should resolve #272. 
- `make install-watch`
- `yvm ls-remote`
- should highlight all installed versions, including current and default
- `yvm ls`
- should show only installed versions, highlighting current and default
- Opted to use a symbol and color instead of text to indicated installed versions

List remote should show installed versions

---

src/commands/install.js

- On a fresh install of YVM, when I was running `yvm use` in a project that had a `.yvmrc` file, I expected it to auto-install the version and it failed instead
- After tracing the code path, I discovered that `installVersion` was being called with incorrect arguments
- Create a folder with a `.yvmrc` file
- In the rc file, put a version number that you don't already have installed
- Run `yvm use`
- Verify that it downloads and installs the specified Yarn version and enables it

fix: invalid version number when running `yvm use` to auto-install version from `.yvmrc` file

---

src/yvm-exec.js

Use native child process over shelljs exec
Fixes #286
FAIL case:
- Install latest
- `yvm exec contributors:add`
- See input fail (and arrow keys)
PASS case:
- Check out this branch
- `yvm exec contributors:add`
- See input succeed (and arrow keys work!)

feat: pipe sidio/stdout/stdin correctly between spawned yarn and parent

---

package.json
yarn.lock

BREAKING CHANGE: Bumped node minimum node version to 8.0 in the previous commit. Minimum node version is now 8.0

feat: 🎸 add commitizen (and bump minimum node version)

---

package.json
src/commands/remove.js
src/commands/which.js
src/util/version.js
src/yvm.js
test/commands/remove.test.js
test/commands/which.test.js
test/util/version.test.js
yarn.lock

- Removed shelljs dependency
- Updates remove logic to use `yarn --version` to check version in use
- Adds tests
- Please `make install-watch`
- `yvm i 1.8.0`
- `yvm ls` confirm version is listed
- `yvm rm 1.8.0` should remove version successfully
- `yvm ls` confirm version not listed
- `yvm use 1.13.0`
- `yvm ls` confirm version listed
- `yvm rm 1.13.0` should not remove version
- `yvm ls` confirm version still listed
- `yarn --version` confirm version still active
- Addresses comments from #290

feat: remove shelljs dependency

---

README.md
docs/faq.md
package.json
src/util/version.js
test/util/__snapshots__/version.test.js.snap
test/util/version.test.js
yarn.lock

- Bumps `cosmiconfig` dependency to support using nested `package.json` prop e.g. `engines.yarn`
- Please `make install-watch`, this PR uses an updated package
- Set the `engines.yarn` property in a projects `package.json` to a valid semver range
- `yvm use` in the directory
- Yarn version in use should be one satisfying the value supplied
- Follow up to https://github.com/tophat/yvm/pull/291#discussion_r249913994
- Addresses comments in #284

feat: use yarn engine in package json

---

src/util/yvmInstalledVersion.js
test/util/__snapshots__/yvmInstalledVersion.test.js.snap
test/util/yvmInstalledVersion.test.js

Should resolve #317
- Does not print error when attempting to get `yvm version`
- uninstall yvm
- `yvm version` should show a regular message
- `YVM_VERBOSE=1 yvm version` should show reason for failure

fix: yarn version output

---

src/yvm.fish
src/yvm.sh
test/sanity-test.sh

Should resolve #316
- Removes dependence on interactive mode
- Refactor `yvm.sh` to function like `yvm.fish`
- Please `make install-watch`
- `yvm ls-remote` Should show list of available versions
- `bash --login -c 'yvm install <version>'` Any version from the list should work
- `yvm ls` Should show list of installed versions
- `bash --login -c 'yvm use <version>'` Any installed version should work
- `bash --login -c 'yvm exec --version'` Should show current yarn version

fix: init yvm function in non interactive shell

---

Makefile

`yvm.sh` was updated to be fully sourceable in #318 which breaks subsequent ci builds

ci: use sourced yvm

---

scripts/install.sh

This PR adds pre-install checks to verify that all of the commands that the install process requires are installed and executable. In the case where it's not, it prints clear messaging about what package is missing and terminates the install process.
You can temporarily remove `unzip` or `curl` from your PATH (or QA inside a Docker container that doesn't have those packages) -- trying to run the install script in those conditions should trigger the preflight check with the appropriate message.
If you run the install script in an environment where both `curl` and `unzip` are well-defined, you should be allowed through normally.

Preflight check on install dependencies

---

src/commands/alias.js
src/commands/exec.js
src/commands/getDefaultVersion.js
src/commands/getNewPath.js
src/commands/install.js
src/commands/list.js
src/commands/listRemote.js
src/commands/remove.js
src/commands/setDefault.js
src/commands/unalias.js
src/util/version.js
src/yvm.js
test/commands/__snapshots__/alias.test.js.snap
test/commands/alias.test.js
test/commands/exec.test.js
test/commands/getDefaultVersion.test.js
test/commands/getNewPath.test.js
test/commands/install.test.js
test/commands/list.test.js
test/commands/remove.test.js
test/commands/setDefault.test.js
test/commands/unalias.test.js

- Moves all logic to the commands and only returns exit codes to the `yvm.js` file
- `yvm help`
- Attempt all commands

chore: standardize exit codes

---

src/util/path.js
test/commands/current.test.js
test/util/alias.test.js

- Replaces `FISH_USER_PATHS` with `fish_user_paths` environment variable for the fish shell, [see docs](https://fishshell.com/docs/current/)
- In your fish config file before the source `yvm.fish` line
```fish
set -U fish_user_paths "/usr/local/bin" $fish_user_paths
```
- Reload fish shell
- `echo $fish_user_paths` will only have the yvm yarn path
- Reload fish shell
- `echo $fish_user_paths` will only have all paths set previously and the yvm yarn path
- Fixes #353

fix: fish user paths

---

src/commands/getNewPath.js
test/commands/getNewPath.test.js

- Deduplicates path when building new path
- Always prepend yvm yarn version in path
- Enter a directory with a .yvmrc that is different from your current yarn version
- yvm use && yarn -v should show the same version as your .yvmrc
- Do the above inside a tmux session
- yvm changes the yarn version
- Fixes #283

fix: build new path without duplicates

---

README.md
scripts/install-watch.sh
scripts/install.js
scripts/tests/install.test.js
src/shim/yarn.js
src/yvm.fish
src/yvm.sh
webpack/webpack.config.base.js

Should resolve #136. All yarn commands will now be shimmed. YVM will look for a `.yvmrc` file to see which version of yarn should be used. If none are found, it will used the last globally set default version of yarn.
- Open a new terminal session. `echo $PATH`. You should see the shim directory at the front of your path.
- Run any yarn command. If you do not have a default yarn version set, this will be executed using the `default` `stable` version.
- Switch into any folder with a .yvmrc file with a yarn version that is not installed. Run a yarn command. This will download and install the yarn version before running the command.

feat: shim yarn commands

---

CHANGELOG.md
src/util/alias.js
src/util/constants.js
test/util/alias.test.js

Switch to using the same link [yarn has internally](https://github.com/yarnpkg/yarn/search?q=SELF_UPDATE_VERSION_URL&unscoped_q=SELF_UPDATE_VERSION_URL) to determine new versions.
- `yvm alias stable`
- `yvm i stable`
- `yvm ls`
- `yvm use stable`
- `yvm rm stable`

fix: use yarn latest version link

---

jsconfig.json
package.json
src/commands/install.js
src/util/download.js
src/util/verification.js
src/yvm.js
test/commands/install.test.js
test/util/verification.test.js
yarn.lock

Fail yarn installation if key is invalid or expired.
- Please `make install-watch`
- `yvm i 1.13.0 --verify` should succeed
- `yvm i 1.7.0 --verify` should fail on expired key
- `yvm i 1.7.0` should warn on expired key
- Previously this verification was performed but not used.

fix: install yarn verification

---

.github/tap-release.yml
src/yvm.fish

There's no need to set yvm variables at universal level. Set at global scope and export to allow child processes access.
- Install fish shell
- Please `make install`, this PR uses a new package
- Launch fish shell
- `which yarn` should point to shimmed yarn
- `yarn --version`
- `yvm use <version>`
- `which yarn` should point to yvm managed yarn version
- `yarn --version`

fix: replace fish universal variable with global export

---

src/commands/current.js
src/util/alias.js
src/util/path.js
test/commands/__snapshots__/alias.test.js.snap
test/commands/alias.test.js
test/commands/current.test.js
test/util/__snapshots__/alias.test.js.snap
test/util/alias.test.js

- Update current command to detect shimmed yarn
- Update alias command to use the helper methods
- `yvm current` does not detect yarn shim version
- `yvm current` should show correct output
- `yvm alias` should show yvm aliases

Current command incompatible with yarn shim

---

package.json
yarn.lock

---
[Find out more about this release](https://github.com/bundlewatch/bundlewatch).
<details>
<summary>FAQ and help</summary>
There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>
---
Your [Greenkeeper](https://greenkeeper.io) bot :palm_tree:

Update bundlewatch to version 0.2.5 🚀

---

.github/tap-release.yml
scripts/install.js
src/commands/configureShell.js
src/yvm.js
test/commands/__snapshots__/configureShell.test.js.snap
test/commands/configureShell.test.js
webpack/webpack.config.dev.js

Fixes #427
- `yvm configure-shell --shell bash --profile ~/.noprofile --yvmDir somerandom/.yvm`
- should fallback to configuring your `.bashrc` or `.bash_profile`
- should create a `somerandom/.yvm` dir with `yvm.sh` and `shim` unpacked
- `touch ~/.noprofile`
- `yvm configure-shell --shell bash --profile ~/.noprofile --yvmDir somerandom/.yvm`
- should configure the `~/.noprofile` with the yvm initialisation
- should create a `somerandom/.yvm` dir with `yvm.sh` and `shim` unpacked

feat: support configurable shell profiles

---

scripts/install.sh

- Pin the yvm version install js being installed
- N/A

fix: pin install version in legacy shell install script

---

Makefile
scripts/install.js
test/scripts/install.test.js

Fixes the install script to account for "v" prefix
- `yarn jest scripts/install -t 'specified version'` should install `v2.4.x` not `v3.2.4`

fix: match version tags with v prefix in install script

---

README.md
src/commands/configureShell.js
test/commands/__snapshots__/configureShell.test.js.snap
test/scripts/install.test.js

Fix fish shell config to check for the existence of the file before sourcing it
- Load fish shell
- `yvm ls-remote`
- Delete yvm.fish
- Reload fish shell
- Should see no errors even if yvm is not loaded

fix: check if yvm script exists in fish shell before sourcing

---

package.json
src/commands/current.js
src/util/version.js
yarn.lock

Bump semver to breaking change version 7.0.0 [change diff](https://github.com/npm/node-semver/compare/v6.3.0...v7.0.0)

chore: bump semver to v7.0.0

---

fake.js
src/shell/yvm.sh
test/scripts/yvm.test.fish
test/scripts/yvm.test.sh

Fixes #756
```bash
make install-watch
```
```bash
$ echo "#!/usr/bin/env node\n\nconsole.log(process.argv)" > "./fake.js"
$ chmod +x "./fake.js"
$ yvm exec fake '*.js'
yarn run v1.22.5
$ /workspace/yvm/node_modules/.bin/fake '*.js'
[
'/home/gitpod/.nvm/versions/node/v12.18.3/bin/node',
'/workspace/yvm/node_modules/.bin/fake',
'*.js'
]
Done in 0.18s.
```
This is likely a breaking change

fix: do not expand variables before calling node script

---

Makefile
src/shell/yvm.fish
src/shell/yvm.sh
src/util/version.js
test/util/version.test.js

- If discovering the config file fails, print error.
- If yvm command fails set exit code rather than exit.
Prior to this PR: Create a directory with a package.json file that has invalid JSON. Run `yvm use`. The shell will exit.
After this PR: Repeat above, and shell will set exit code rather than exit.
I believe the shell function also needs some error handling.

fix: exception when reading yvm config fails, close #926
